spring.application.name=libraryapi
spring.profiles.active=dev
spring.jpa.open-in-view=false

spring.security.oauth2.client.registration.google.client-id=${client-id}
spring.security.oauth2.client.registration.google.client-secret=${client-secret}

logging.file.name=app.log
logging.level.root=INFO
logging.level.io.github.marcos.libraryapi=WARN